### ISSUE TITLE
Enhancement Request: Add datasweet formula to region maps in kibana

### ISSUE THREAD

**Issue by georgezoto** [datasweet/kibana-datasweet-formula#13]
Hello datasweet team,

I wanted to ask if you plan to add the amazing datasweet formula feature for `regionmaps` as well in kibana. What about other types of visualizations like coordinate maps or pie charts?

<img width="675" alt="region maps" src="https://user-images.githubusercontent.com/16548373/40199069-5bda9280-59e6-11e8-8ac9-47b3a6820aef.png">

Thank you again,
George

**Comment by tcharlot-datasweet** [comment]
Hi @georgezoto 

For now, the region map is defined as below :
```javascript
 schemas: new Schemas([
        {
          group: 'metrics',
          name: 'metric',
          title: 'Value',
          min: 1,
          max: 1,
          aggFilter: ['count', 'avg', 'sum', 'min', 'max', 'cardinality', 'top_hits',
            'sum_bucket', 'min_bucket', 'max_bucket', 'avg_bucket'],
          defaults: [
            { schema: 'metric', type: 'count' }
          ]
        },
        {
          group: 'buckets',
          name: 'segment',
          icon: 'fa fa-globe',
          title: 'shape field',
          min: 1,
          max: 1,
          aggFilter: ['terms']
        }
      ])
}
```

So to add datasweet_formula to region map, we have to tweak the region_map definition. 
I am not sure this is a good thing.
