### ISSUE TITLE
order by in bucket  by formular not working

### ISSUE THREAD

**Issue by freakwave1111** [datasweet/kibana-datasweet-formula#20]
Hi,
I really like your plugin. The only issue I have is when I try to use the new calculated metric to order my buckets, I am getting:

TypeError: Cannot read property 'filters' of undefined
    at http://localhost:5601/bundles/commons.bundle.js?v=16627:27:173794
    at Array.forEach (<anonymous>)
    at recurse (http://localhost:5601/bundles/commons.bundle.js?v=16627:27:173744)
    at http://localhost:5601/bundles/commons.bundle.js?v=16627:27:173939
    at Array.forEach (<anonymous>)
    at recurse (http://localhost:5601/bundles/commons.bundle.js?v=16627:27:173744)
    at http://localhost:5601/bundles/commons.bundle.js?v=16627:27:173977
    at processQueue (http://localhost:5601/bundles/vendors.bundle.js?v=16627:58:132456)
    at http://localhost:5601/bundles/vendors.bundle.js?v=16627:58:133349
    at Scope.$digest (http://localhost:5601/bundles/vendors.bundle.js?v=16627:58:144239)

![orderby](https://user-images.githubusercontent.com/36045110/42968787-995d2434-8ba4-11e8-8e5a-db5c5be630a8.png)

![image](https://user-images.githubusercontent.com/36045110/42968915-f349e0fe-8ba4-11e8-82a2-98d6f481c8ca.png)

Kind regards,

Wolfgang

**Comment by lfroment-datasweet** [comment]
Hi Wolfgang,
first and foremost,  Formula is processed within Kibana, this means you cannot ask Elasticsearch to order buckets based on Formula values, it simply does not see those values...
But you first "order by" should not throw an error if it is based on an existing field in the index. we will try to reproduce. Is your Agg1 a scripted field? What is its mapping?

Regards
