### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by RaihanaAaba** [datasweet/kibana-datasweet-formula#21]
I have tried to install this plugin in kibana version 6.2.1 but i've got the error "Plugin installation was unsuccessful due to error "No valid url specified."". Can you please help me !!

**Comment by tcharlot-datasweet** [comment]
Hi @RaihanaAaba 

To install the plugin, please refer to the kibana doc : https://www.elastic.co/guide/en/kibana/6.2/install-plugin.html

```
kibana-plugin install file://<ABSOLUTE PATH OF THE ZIP FILE>
```
