### ISSUE TITLE
Aggregate metrics don't respect split series

### ISSUE THREAD

**Issue by huttj** [datasweet/kibana-datasweet-formula#25]
I'm trying to normalize the plots of several different streams of data, and plot them together. Datasweet Formula lets me get really, really close, but I need to aggregate the individual series, not *all* of the data.

My formula is `agg1 / sum(agg1)`, and my `agg1` is just a count. With five different series, the top one maxes out at a little over 14%:

![image](https://user-images.githubusercontent.com/5355453/44546855-17594400-a6ce-11e8-854b-ed1ad8df5a05.png)

When I filter down to just that value, it becomes 50%:

![image](https://user-images.githubusercontent.com/5355453/44546879-27712380-a6ce-11e8-968a-504d0418d29a.png)

I want it to be 50% in both cases, but `sum(agg1)` gives me the sum of **all** of the data, not just the data for the one series.

I would expect that my use case here is the more common one. Not sure, though.

**Comment by huttj** [comment]
From digging through the code, it looks like supporting this with the syntax from my query (`agg1 / sum(agg1)`) would be very tricky.

I was able to achieve the desired functionality by creating a function that would take a value, as well as the labels, and do the calculation I want on those:

```
export default new FormulaFunction('percentage', {
  help: 'Calculate values in a split series as percentage of the total of their individual series.',
  fn: function (series, names) {
    const totals = names.reduce((acc, n, i) => {
      acc[n] = (acc[n] || 0) + series[i];
      return acc;
    }, {});
    return series.map((n, i) => n / totals[names[i]]);
  }
});
```

Of course, this probably isn't the only case in which one might want to do an aggregate calculation on a split series, so it might be worth it to figure out how to generalize this.

**Comment by lfroment-datasweet** [comment]
Hi @huttj, thanks for your message. Indeed, it is worth a closer look. If you want to contribute, feel free to share some code. Are you in a position to do so? It might otherwise take us some time to check what can be done.

Regards
