### ISSUE TITLE
The data has not changed

### ISSUE THREAD

**Issue by ZhaoBaymax** [datasweet/kibana-datasweet-formula#31]
I use the Metric Visualize.  Calculate the difference between access and error in the log, filter out less than 0。 when i change timestamp, the data did not changed. 
![image](https://user-images.githubusercontent.com/28599497/48106092-f20fb700-e274-11e8-838b-9fa32a950cb1.png)

**Comment by lfroment-datasweet** [comment]
Hi @ZhaoBaymax , please provide us with the Kibana version and Formula release you were using. We cannot reproduce.

**Comment by ZhaoBaymax** [comment]
> Hi @ZhaoBaymax , please provide us with the Kibana version and Formula release you were using. We cannot reproduce.

kibana version: 6.3.0 
Formula : version 1.1.2 and 1.1.1 tried , but it did not work .
