### ISSUE TITLE
Divide by 0 warning.

### ISSUE THREAD

**Issue by joeyJsonar** [datasweet/kibana-datasweet-formula#32]
Javascript have some weird behaviour concerning division.
* 0/0 => NaN
* x/0 | x <> 0 => -/+Infinity

We want NaN for both.

Our organizationalso wanted to display a Kibana warning when a Divide by 0 occured, just to warn the user. Let them know that something unexpected **might** be hapenning. Something like the following:

> 'Divide by 0 occured. If this is unexpected, please ensure the denominator is non-zero.'

Let me know what you think.

**Comment by guanghaofan** [comment]
can we show all the x/0 as null?
