### ISSUE TITLE
Kibana 6.5.1 Support

### ISSUE THREAD

**Issue by qakart** [datasweet/kibana-datasweet-formula#36]
HI any idea when we will get the release for 6.5.1 or is there any workaround to get it work

**Comment by seomehard** [comment]
Will be great to support 6.6 version. It's a great plugin and a lot of people wait for you guys :)

**Comment by tcharlot-datasweet** [comment]
Hi, 
please give it a try to the last release (support for kibana v6.5.x to 6.7.x).
Regards
