### ISSUE TITLE
kibana cannot be ordered by metrics that are aggregated with Datasweet Formula

### ISSUE THREAD

**Issue by qiuyujing** [datasweet/kibana-datasweet-formula#37]
Hello,

Kibana version: 6.4.0
datasweet-formula: 2.0.0
Problem: kibana cannot be ordered by the metrics that are aggregated with Datasweet Formula。The metric that is aggregated with Datasweet Formula can be seen in “order by”, but it doesn't work。
![image](https://user-images.githubusercontent.com/35557511/50883902-5c370a80-1424-11e9-9c76-15f55591fa04.png)

**Comment by lfroment-datasweet** [comment]
Hi @qiuyujing 
that is a normal behavior. Formula generates its results in the kibana context, based on the ES results. ES knows nothing about Formula, thus, it cannot order a bucket by a Formula result.
