### ISSUE TITLE
Datasweet formula plugin is breaking SearchGuard configuration tabs

### ISSUE THREAD

**Issue by skbly7** [datasweet/kibana-datasweet-formula#39]
Hi, the datasweet plugin is not working properly when installed on Kibana with SearchGuard.

Steps to reproduce:
1. Install Kibana with SearchGuard plugin. Tested on below versions:
- Kibana 6.4.0 `https://artifacts.elastic.co/downloads/kibana/kibana-6.4.0-linux-x86_64.tar.gz`
- SearchGuard 15 for 6.4.0 `http://central.maven.org/maven2/com/floragunn/search-guard-kibana-plugin/6.4.0-15/search-guard-kibana-plugin-6.4.0-15.zip`
- DataSweet Formula 2.0.0 for 6.4.0 `https://github.com/datasweet/kibana-datasweet-formula/releases/download/v2.0.0/datasweet_formula-2.0.0_kibana-6.4.0.zip`
2. Once you have SearchGuard running install datasweet formula plugin
```
Attempting to transfer from file:///tmp/kibana/datasweet_formula-2.0.0_kibana-6.4.0.zip
Transferring 407760 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation complete
```
3. Open SearchGuard configuration or tenancy selection pages, which will not be rendered. `/app/searchguard-configuration` and `/app/searchguard-multitenancy`
![image](https://user-images.githubusercontent.com/3490586/52129477-9a0f0380-265d-11e9-9aa8-6794c0877419.png)

I have tried installing other plugins instead of datasweet and SearchGuard pages don't break due to them. Hence, opening issue in this project. Please let me know if I should share some more information.

**Comment by skbly7** [comment]
NOTE: Tested the same with SearchGuard version 17. The error exist with it as well.

**Comment by tcharlot-datasweet** [comment]
Hi !

Datasweet Formula is a big hack of the kibana code : we decorate (angular pattern) some kibana core functions to run. 
We are sorry, we won't assure compliance with others plugins.

Regards.
