### ISSUE TITLE
make plugin not dependent on version,

### ISSUE THREAD

**Issue by g-d** [datasweet/kibana-datasweet-formula#40]
With every new minor version of kibana and dedicated version number of the datasweet plug-in is needed. There are no available version for the latest version of Kibana. Would it be possible to remove the version checking mechanisms?

**Comment by tcharlot-datasweet** [comment]
Hi.
Actually, we only support kibana v5.6.x to v6.4.x. 
They are a lot of breaking changes in v6.5.x, and for now, we don't have the time to do the upgrade.

**Comment by emveee** [comment]
@tcharlot-datasweet is there a timeline of when you guys will have time to upgrade the plugin above 6.4.x?

**Comment by tcharlot-datasweet** [comment]
Hi, 
please give it a try to the last release (support for kibana v6.5.x to 6.7.x).
Regards
