### ISSUE TITLE
Data-Sweet-formula is not throwing "this.viz is not defined" error with kibana 6.6.2

### ISSUE THREAD

**Issue by sujata00** [datasweet/kibana-datasweet-formula#41]
Hi,

I am working with kibana 6.6.1. I have to install data-sweet-formula plugin manually to work on this version of kibana. Unfortunately, after successful installation kibana is throwing "this.viz is not defined" error.

Can you please look into this issue.

Regards,
Sujata

**Comment by tcharlot-datasweet** [comment]
Hi, 

For now, the plugin is not compatible with kibana version >= 6.5.0

**Comment by tcharlot-datasweet** [comment]
Hi, 
please give it a try to the last release (support for kibana v6.5.x to 6.7.x).
Regards
