### ISSUE TITLE
kibana-datasweet-formula for kibana 6.7.1

### ISSUE THREAD

**Issue by gilmau** [datasweet/kibana-datasweet-formula#46]
We use Kibana 6.2 and we want to upgrade to 6.7
I'd install Kibana 6.7.1 on my computer to try it, but I can't install the datasweet-formula. 

this is the error i get:
 FATAL  Error: Optimizations failure.
   5656 modules

    ERROR in ./plugins/datasweet_formula/public/decorators/lib/formula_parser.js
    Module not found: Error: Can't resolve 'expr-eval' in 'C:\Users\gilm\Desktop\elk 6.7.1\kibana-6.7.1-windows-x86_64\plugins\datasweet_formula\public\decorators\lib'

    ERROR in ./plugins/datasweet_formula/public/formulas/percentile.js
    Module not found: Error: Can't resolve 'percentile' in 'C:\Users\gilm\Desktop\elk 6.7.1\kibana-6.7.1-windows-x86_64\plugins\datasweet_formula\public\formulas'

Maybe you have a solution?

**Comment by lfroment-datasweet** [comment]
@tcharlot-datasweet

**Comment by charlotth** [comment]
Hi @gilmau
Try the new release v2.1.2
https://github.com/datasweet/kibana-datasweet-formula/releases/tag/v2.1.2
