### ISSUE TITLE
kibana-datasweet-formula for kibana-6.2.3

### ISSUE THREAD

**Issue by zhousilong** [datasweet/kibana-datasweet-formula#48]
./bin/kibana-plugin install https://github.com/datasweet-fr/kibana-datasweet-formula/releases/download/version_name/datasweet_formula-1.1.3_kibana-major.minor.patch.zip

Plugin installation was unsuccessful due to error "No valid url specified."

what's wrong?

**Comment by charlotth** [comment]
HI @zhousilong 
The release 1.1.3 is only accessible via the source code (you have to compile by yourself)
You can use the release 1.1.2: https://github.com/datasweet/kibana-datasweet-formula/releases/tag/v1.1.2

```sh
./bin/kibana-plugin install https://github.com/datasweet/kibana-datasweet-formula/releases/download/v1.1.2/datasweet_formula-1.1.2_kibana-6.2.3.zip
```
