### ISSUE TITLE
Datasweet does not count sum aggregation in Kibana

### ISSUE THREAD

**Issue by webmasterThomas** [datasweet/kibana-datasweet-formula#49]
Hi team,
i calculated some fields and then tried to display the sum of total for my fields, but it didnt work. Sum aggregation displays nothing, however f.e max aggregation works and shows the results
any help or it`s a bug? My Kibana is 6.7.0

**Comment by lfroment-datasweet** [comment]
Hi, can you please post your agg settings (screenshot?). We cannot reproduce your problem.

**Comment by webmasterThomas** [comment]
> 
> 
> Hi, can you please post your agg settings (screenshot?). We cannot reproduce your problem.

Hi, screenshots are below. so it does not work when aggregations are hidden and my task was to count the difference between my max and min fields and show only this difference in table and hide intermediate fields. 
![Screenshot_2](https://user-images.githubusercontent.com/48207254/58156383-9e981000-7c7e-11e9-96d3-d549bc40d004.png)
![Screenshot_1](https://user-images.githubusercontent.com/48207254/58156384-9f30a680-7c7e-11e9-9ac2-202e24f933ae.png)

**Comment by tcharlot-datasweet** [comment]
Hi, 

Yeah this is a bug but it will be difficult to resolve it. 
Indeed, the "total" part of kibana is executed on the final table.
So, if a column is hidden, the final table has not the column and the plugin can't calculate the total part... :/
