### ISSUE TITLE
Problem to install in Elastic 5.6.8 and Centos 6

### ISSUE THREAD

**Issue by albunn** [datasweet/kibana-datasweet-formula#51]
Good afternoon

I'm trying to install this plugin in a Kibana 5.6.8 that's is part of an ElasticSearch 5.6.8 Cluster. The operational sysmtem is Centos 6.

# /usr/share/kibana/bin/kibana-plugin install https://codeload.github.com/datasweet/kibana-datasweet-formula/tar.gz/v1.1.3
Attempting to transfer from https://codeload.github.com/datasweet/kibana-datasweet-formula/tar.gz/v1.1.3
Transferring unknown number of bytes
Transfer complete
Retrieving metadata from plugin archive
Error: end of central directory record signature not found
    at /usr/share/kibana/node_modules/yauzl/index.js:179:14
    at /usr/share/kibana/node_modules/yauzl/index.js:539:5
    at /usr/share/kibana/node_modules/fd-slicer/index.js:32:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:683:17)
Plugin installation was unsuccessful due to error "Error retrieving metadata from plugin archive"

Do you have any idea?

Thanks

Regards

Alexandre Bunn

**Comment by lfroment-datasweet** [comment]
Hi @albunn 
I think you are having trouble because the release 1.1.3 is only accessible via the source code (you have to compile by yourself)
You can use the release 1.1.2: https://github.com/datasweet/kibana-datasweet-formula/releases/tag/v1.1.2


best regards
