### ISSUE TITLE
Problem with datasweet clash with custom plugins

### ISSUE THREAD

**Issue by zxjczero** [datasweet/kibana-datasweet-formula#68]
I'm working with the datasweet plugin (datasweet_formula-2.1.2_kibana-6.8.0
) for Kibana 6.8.3.datasweet plugin can work,but other custom plugins Open to blank.How should I do to fix

**Comment by lfroment-datasweet** [comment]
Hi @zxjczero. I'm not sure I understand your problem. Could you be more specific?
Moreover, we are looking for help to maintain, so we are not in a position to work on newer versions of the plugin. 
Elastic makes it very difficult by introducing breaking changes very frequently in Kibana releases.

**Comment by pchakour** [comment]
I already had this issue with custom plugins. To fix it, you have to change the  ``public/formula_hack.js`` file.

Remove the following line:
``` javascript
import { decorateAggTypes } from './decorators/agg_types';
```

And after the following line:
``` javascript
if (appId === 'kibana' || appId === 'dashboardViewer') {
```

Add these lines:
``` javascript
// Include agg_types only when necessary else custom plugin will not work (blank page)
const decorateAggTypes = require('./decorators/agg_types').decorateAggTypes;
```

**Comment by zxjczero** [comment]
@pchakour Thanks a million！
