### ISSUE TITLE
unable to find usable node.js executable

### ISSUE THREAD

**Issue by ghost** [datasweet/kibana-datasweet-formula#73]
Hi team, i m running "./bin/kibana-plugin install  https://github.com/datasweet-fr/kibana-datasweet-formula/releases/download/version_name/datasweet_formula-2.2.1_kibana-7.0.1.zip" and getting the error "unable to find usable node.js executable". Can you help ?

**Comment by lfroment-datasweet** [comment]
Hi @webmasterThomas , it seems this issue is not related to the plugin itself. Maybe this can help you fix it : https://discuss.elastic.co/t/unable-to-find-usable-node-js-executable-while-installing-plugin/233146

**Comment by ghost** [comment]
Hi @lfroment-datasweet , i used both variants listed in this reference and also copying plugin files to plugins forlder also does not work.

**Comment by ghost** [comment]
resolved on my own
